[package]
name = "repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
core = { path = "../core"}
interpreter = { path = "../interpreter"}
rustyline = "14.0.0"
